AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true

Metrics/LineLength:
  Enabled: false

MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false
